// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`resolveTaskFn chunked tasks should handle unexpected error 1`] = `
"× test got an unexpected error.
Unexpected Error"
`;

exports[`resolveTaskFn chunked tasks should throw error for failed linters 1`] = `
"


× mock-fail-linter found some errors. Please fix them and try committing again.
Mock error"
`;

exports[`resolveTaskFn chunked tasks should throw error for killed processes 1`] = `
"


‼ mock-killed-linter was terminated with SIGINT"
`;
